import * as React from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import { MapViewProvider } from "../views/mapview/map-view-context";
import * as data from "../views/mapview/data/data.json";
import * as Comer from "../views/mapview/data/Comer.json";
import * as Playas from "../views/mapview/data/Playas.json";
import * as Sitios from "../views/mapview/data/Sitios.json";
import { Collection } from "../views/mapview/types/collection";
import { MapPage } from "../views/mapview/map-page";
import { useHttp } from "hooks/useHttp";
import { useQuery } from "react-query";

function fetchCollectionById(id: string) {
  return useHttp.get<any>(`collections/${id}`).then((res) => res.data);
}
export default function Map() {
  const collectionsQuery = useQuery<any, Error>(
    ["collections", "616606d42aa42b002e4a005d"],
    () => fetchCollectionById("616606d42aa42b002e4a005d")
  );

  return (
    <div>
      <Head>
        <title>Mapview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {collectionsQuery.data && (
        <MapViewProvider initialData={collectionsQuery.data}>
          <MapPage mapView={<></>} />
          {/*<MapPage mapView={MapView} />*/}
        </MapViewProvider>
      )}
    </div>
  );
}
