import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useAuthContext } from "../context/auth/auth-context";
import { MapView } from "../views/mapview/map-view";

export default function Map() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MapView />
    </div>
  );
}
