import Head from "next/head";
import dynamic from "next/dynamic";
import * as React from "react";
import { MapViewProvider } from "../views/mapview/map-view-context";
import * as data from "../views/mapview/data/data.json";
import * as Comer from "../views/mapview/data/Comer.json";
import * as Playas from "../views/mapview/data/Playas.json";
import * as Sitios from "../views/mapview/data/Sitios.json";
import { Collection } from "../views/mapview/types/collection";
import { PlacesList } from "../views/mapview/components/places-list";
import { FeatureView } from "../views/mapview/components/feature-view";
import { useEffect, useRef, useState } from "react";

export default function Map() {
  const MapView = React.useMemo(
    () =>
      dynamic(
        // @ts-ignore
        () => import("../views/mapview/components/map-view"), // replace '@components/map' with your component's location
        { loading: () => <p>A map is loading</p>, ssr: false } // This line is important. It's what prevents server-side render
      ),
    []
  );

  const dataArr = [
    Playas as Collection,
    Comer as Collection,
    Sitios as Collection,
    data as Collection,
  ];
  return (
    <div>
      <Head>
        <title>Mapview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MapViewProvider initialData={dataArr}>
        <div className="flex max-h-[85vh]">
          <div className="w-2/6 bg-blue-100 flex flex-col">
            <div className=" overflow-y-scroll">
              <PlacesList />
            </div>
            <div className="bg-blue-400 py-8">
              <h3>Collection: Tenerife</h3>
              <h4>Created By: Fer</h4>
            </div>
          </div>
          <div className="w-4/6 overflow-y-scroll relative">
            <div className="z-10">
              <MapView mapdata={data as Collection} />
            </div>
            <FeatureView />
          </div>
        </div>
      </MapViewProvider>
    </div>
  );
}
